name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Check out code
        uses: actions/checkout@v3

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10" 

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Run linting with Black and nbqa
      - name: Run Black and nbqa
        run: |
          black --check .
          nbqa black --check .

      # Step 5: Run tests with coverage
      - name: Run tests and collect coverage
        run: |
          pytest --cov=src --cov-report=xml --cov-report=term-missing tests/

      # Step 6: Upload coverage report as an artifact (optional)
      - name: Upload coverage report
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: coverage.xml
